<?php

/**
 * Implementation of hook_form_alter()
 */
function gsb_fpp_customization_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form') {

    global $user;
    
    workbench_access_user_load_data($user);
    $active = workbench_access_get_active_tree();
    $account_access = array_keys($user->workbench_access);

    $category = array();

    foreach ($account_access as $key => $value) {
      if (isset($active['tree'][$value])) {
        $category = $active['tree'][$value]['name'];
        $categories[$category] = $category;
      }
    }

    if (isset($form_state['process_input']) && $form_state['process_input'] == TRUE) {
      $form['reusable']['category']['#value'] = $form_state['input']['category'];
    } else {
      $form['reusable']['category']['#value'] = '';
    }
    
    $form['reusable']['category']['#type'] = 'select';
    $form['reusable']['category']['#options'] = $categories;

  }

}

/**
 * Preprocess the panels_add_content_modal() function to add the HTML for the preview
 */
function gsb_fpp_customization_preprocess_panels_add_content_modal(&$vars) {

    global $user;

    workbench_access_user_load_data($user);
  
    $active = workbench_access_get_active_tree();
    $active_category_ids = array_keys($active['tree']);
    
    $workbench_access = $user->workbench_access;
  
    // find the categories that are not accessable to the user ...
  
    $remove_items = array();

    foreach ($active_category_ids as $key => $value) {
      if (!isset($workbench_access[$value])) {
        $remove_items[] = $active['tree'][$value]['name'];
      }
    }
    
    // ... and remove them from the list that is displayed

    foreach($remove_items as $key => $value) {
      if (isset($vars['categories'][$value])) {
        $index = array_search($value,array_keys($vars['categories']));
        unset($vars['categories'][$value]);
        unset($vars['categories_array'][$index]);
      }
    }


}

