<?php

/**
 * Implements hook_module_implements_alter()
 */
function gsb_fpp_customization_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    $group = $implementations['gsb_fpp_customization'];
    unset($implementations['gsb_fpp_customization']);
    $implementations['gsb_fpp_customization'] = $group;
  }
}

/**
 * Implements hook_library()
 */
function gsb_fpp_customization_library() {

  $libraries['superfish'] = array(
    'title' => 'Superfish',
    'website' => 'https://github.com/joeldbirch/superfish',
    'version' => '1.7.3',
    'js' => array(
      drupal_get_path('profile', 'gsb_public') . '/libraries/superfish/js/hoverIntent.js' => array(),
      drupal_get_path('profile', 'gsb_public') . '/libraries/superfish/js/superfish.js' => array(),
    ),
    'css' => array(
      drupal_get_path('profile', 'gsb_public') . '/libraries/superfish/css/superfish.css' => array(),
      drupal_get_path('profile', 'gsb_public') . '/libraries/superfish/css/superfish-vertical.css' => array(),
    ),
  );

  $libraries['gsb_fpp_customization'] = array(
    'title' => 'GSB Fpp Customization',
    'website' => 'https://github.com/gsbitse/gsb_fpp_customization',
    'version' => '',
    'js' => array(
      drupal_get_path('module', 'gsb_fpp_customization') . '/js/gsb_fpp_customization.js' => array(),
    ),
    'dependencies' => array(
      array('gsb_fpp_customization', 'superfish'),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_form_FORM_ID_alter()
 *
 * This function will add back the cancel button that panopoly_magic had removed
 */
function gsb_fpp_customization_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['buttons']['cancel']['#access'])) {
    unset($form['buttons']['cancel']['#access']);
  }
}

/**
 * This function will add a select dropdown with the workbench sections as option
 * choices for the user.
 */
function gsb_fpp_customization_form_alter(&$form, &$form_state, $form_id) {
  
  if ($form_id == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form') {

    global $user;

    // only show the pane categories the user has wb access to

    workbench_access_user_load_data($user);
    $active = workbench_access_get_active_tree();
    $account_access = array_keys($user->workbench_access);

    $categories = array();

    foreach ($account_access as $key => $value) {
      if (isset($active['tree'][$value])) {
        $category = $active['tree'][$value]['name'];
        $categories[$category] = $category;
      }
    }

    // adjust the visibility of reusable checkbox

    if (!empty($categories)) {
      if (isset($form_state['process_input']) && $form_state['process_input'] == TRUE) {
        $form['reusable']['category']['#value'] = $form_state['input']['category'];
      } else {
        $form['reusable']['category']['#value'] = '';
      }

      $form['reusable']['category']['#type'] = 'select';
      $form['reusable']['category']['#options'] = $categories;
    }
    else {
      $form['reusable']['#access'] = FALSE;
    }

    // adjust the view_mode

    list($panels_module, $type) = explode(':', $form_state['display']->cache_key);

    $form['view_mode']['#type'] = 'value';
  
    if ($form['#bundle'] == 'existing_node' && $panels_module == 'panels_mini' &&
        in_array($type, array('business_insights', 'faculty_research', 'our_programs', 'the_stanford_gsb_experience'))) {
      $form['view_mode']['#value'] = 'megamenu';
    }
    else {
      $form['view_mode']['#value'] = 'full';
    }

    // hide the title field
    $form['title']['#access'] = FALSE;

    // hide the 'make title a link' field
    $form['link']['#access'] = FALSE;

    // hide the revision field and...
    // set the value to always be false
    $form['revision']['#access'] = FALSE;
    $form['revision']['revision']['#value'] = 0;

  }
}

/**
 * Preprocess the panels_add_content_modal() function to remove any
 * categories (workbench sections) that the user doesn't have access to.
 */
function gsb_fpp_customization_preprocess_panels_add_content_modal(&$vars) {

    global $user;

    drupal_add_library('gsb_fpp_customization', 'gsb_fpp_customization');

    workbench_access_user_load_data($user);

    $active = workbench_access_get_active_tree();
    $active_category_ids = array_keys($active['tree']);

    $workbench_access = $user->workbench_access;

    // find the categories that are not accessable to the user ...

    $remove_items = array();

    foreach ($active_category_ids as $key => $value) {
      if (!isset($workbench_access[$value])) {
        $remove_items[] = $active['tree'][$value]['name'];
      }
    }

    // ... and remove them from the list that is displayed

    $index = 0;
    foreach($vars['categories'] as $key => $value) {
      if ($key == 'root') {
        continue;
      }
      if (in_array($key, $remove_items)) {
        unset($vars['categories_array'][$index]);
        unset($vars['categories'][$key]);
      }
      $index++;
    }
}
